name = "INIBuilder"
uuid = "f73d3ad2-b0c7-11e9-1f44-136428e9be6c"
authors = ["Ranjan Anantharaman <ranjan.anantharaman@gmail.com>"]
version = "0.1.0"

[deps]
Circuitscape = "2b7a1792-8151-5239-925d-e2b8fdfa3201"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
